#!/bin/bash -ex

# Install Ubuntu packages
export DEBIAN_FRONTEND=noninteractive
sudo apt-get update
sudo apt-get install -y \
    python-pip \
    python-requests \
    socat

# Install Python packages
sudo pip install pylint==1.3.1
sudo pip install pexpect==4.0.1
sudo pip install ptyprocess==0.5
sudo pip install requests==2.9.1
sudo pip install wheel==0.26.0
sudo pip install xlrd==0.9.4
sudo pip install elasticsearch==1.3.0
sudo pip install thrift==0.9.1
suod pip install Pillow==3.2.0
